name: "Supported Services Matrix Calculator"
author: "Mage-OS"
description: "Calulate a matrix of all supported services (based off supported-services.json)"


inputs:
  repository:
    description: "Repository"
    required: true
  ref:
    description: "head SHA"
    required: true

outputs:
  php_versions: 
    description: fooooo
    value: ${{ steps.set-matrix.outputs.php_versions }}
  # database_versions: 
  #   value: ${{ steps.set-matrix.outputs.database_versions }}
  # search_versions: 
  #   value: ${{ steps.set-matrix.outputs.search_versions }}
  # message_queue_versions: 
  #   value: ${{ steps.set-matrix.outputs.message_queue_versions }}
  # cache_versions: 
  #   vaule: ${{ steps.set-matrix.outputs.cache_versions }}
  # http_cache_versions: 
  #   value: ${{ steps.set-matrix.outputs.http_cache_versions }}

runs:
  using: "composite"
  steps:
    - name: debug
      shell: bash
      run: |
        echo "yo yoy yo"

    - name: Checkout PR commit
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - id: set-matrix
      name: Calculate Matrix
      shell: bash
      run: |
        echo "php_versions=$(jq -c .services.php supported-services.json)" >> "$GITHUB_OUTPUT"
        echo "database_versions=$(jq -c .services.database supported-services.json)" >> "$GITHUB_OUTPUT"
        echo "search_versions=$(jq -c .services.search supported-services.json)" >> "$GITHUB_OUTPUT"
        echo "message_queue_versions=$(jq -c .services.message_queue supported-services.json)" >> "$GITHUB_OUTPUT"
        echo "cache_versions=$(jq -c .services.cache supported-services.json)" >> "$GITHUB_OUTPUT"
        echo "http_cache_versions=$(jq -c .services.http_cache supported-services.json)" >> "$GITHUB_OUTPUT"

    - name: Debug output
      shell: bash
      run: |
        echo "PHP Versions: ${{ steps.set-matrix.outputs.php_versions }}"
        echo "database Versions: ${{ steps.set-matrix.outputs.database_versions }}"
        echo "search Versions: ${{ steps.set-matrix.outputs.search_versions }}"
        echo "message_queue Versions: ${{ steps.set-matrix.outputs.message_queue_versions }}"
        echo "cache Versions: ${{ steps.set-matrix.outputs.cache_versions }}"
        echo "http_cache Versions: ${{ steps.set-matrix.outputs.http_cache_versions }}"
