name: testing
on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "test"
        
  matrix-calculator:
    uses: ./supported-services-matrix-calculator/action.yml@main
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.pr_head }}