name: testing
on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true

jobs:
  matrix-calculator:
    runs-on: ubuntu-latest
    steps:
      - name: debug2
        shell: bash
        env:
          repository: ${{ inputs.repository }}
          pr_head: ${{ inputs.pr_head }}
          pr_base: ${{ inputs.pr_base }}
        run: |
          echo "input was"
          echo "repository: ${repository}"
          echo "pr_head: ${pr_head}"
          echo "pr_base: ${pr_base}"

      - name: blah blah
        id: calculate-matrix
        uses:  adamzero1/mageos-github-actions/supported-services-matrix-calculator@main
        # uses: mage-os/github-actions/get-magento-version@main
        with:
          # working-directory: foo
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.pr_head }}

      - name: calc result
        shell: bash
        env:
          php_versions: ${{ steps.calculate-matrix.outputs.php_versions }}
          database_versions: ${{ steps.calculate-matrix.outputs.database_versions }}
          search_versions: ${{ steps.calculate-matrix.outputs.search_versions }}
          message_queue_versions: ${{ steps.calculate-matrix.outputs.message_queue_versions }}
          cache_versions: ${{ steps.calculate-matrix.outputs.cache_versions }}
          http_cache_versions: ${{ steps.calculate-matrix.outputs.http_cache_versions }}
        run: |
          echo "PHP Versions: $php_versions"
          echo "database_versions: $database_versions"
          echo "search_versions: $search_versions"
          echo "message_queue_versions: $message_queue_versions"
          echo "cache_versions: $cache_versions"
          echo "http_cache_versions: $http_cache_versions"
      
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: debugalilly
        shell: bash
        run: |
          echo "scccccccooooooooooby!?"

  # matrix-calculator:
  #   uses:  mage-os/github-actions/supported-services-matrix-calculator@main
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.pr_head }}