name: testing
on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: "Repository"
        required: true
      pr_head:
        type: string
        description: "head SHA"
        required: true
      pr_base:
        type: string
        description: "pr base SHA"
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug2
        shell: bash
        env:
          repository: ${{ inputs.repository }}
          pr_head: ${{ inputs.pr_head }}
          pr_base: ${{ inputs.pr_base }}
        run: |
          echo "input was"
          echo "repository: ${repository}"
          echo "pr_head: ${pr_head}"
          echo "pr_base: ${pr_base}"

      - name: blah blah
        id: calculate-matrix
        uses:  adamzero1/mageos-github-actions/supported-services-matrix-calculator@main
        # uses: mage-os/github-actions/get-magento-version@main
        with:
          # working-directory: foo
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.pr_head }}

      - name: calc result
        shell: bash
        env:
          php_versions: ${{ steps.calculate-matrix.outputs.php_versions }}
        run: |
          echo "PHP Versions: $php_versions"
        
  # matrix-calculator:
  #   uses:  mage-os/github-actions/supported-services-matrix-calculator@main
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.pr_head }}